[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Updated: 2025-01-28 - Force rebuild after fixing Dashboard syntax errors and calculator link
